// client/app/art-details/[id]/ArtDetails.tsx
'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { toast, Toaster } from 'sonner'
import { ImageCarousel } from './components/ImageCarousel'
import { getArtworkDetails, handleReaction, addComment, addReply, handleCommentReactionApi } from './actions'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { formatPrice } from '@/lib/utils'
import { ThumbsUp, ThumbsDown, Plus, ShoppingCart } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabaseClient'
import { useCartStore } from '@/lib/store/cart'

interface Artist {
  name: string
  avatar_url: string
  id: string
}

interface RelatedArtwork {
  id: string
  title: string
  image: string
}

interface Comment {
  id: string
  name: string
  avatar_url: string
  comment: string
  created_at: string
  user_id: string
  userReaction: 'like' | 'dislike' | null
  likeCount: number
  dislikeCount: number
  replies?: Comment[]
}

interface ArtworkDetails {
  id: string
  title: string
  description: string
  price: number
  images: string[]
  category: string
  artist: Artist
  relatedArtworks: RelatedArtwork[]
  reactions: {
    likeCount: number
    dislikeCount: number
  }
  comments: Comment[]
}

interface ArtworkResponse {
  artwork?: ArtworkDetails
  error?: string
}

export default function ArtDetails({ id }: { id: string }) {
  const router = useRouter()
  const [artwork, setArtwork] = useState<ArtworkDetails | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [likeCount, setLikeCount] = useState(0)
  const [dislikeCount, setDislikeCount] = useState(0)
  const [userReaction, setUserReaction] = useState<'like' | 'dislike' | null>(null)
  const [comments, setComments] = useState<Comment[]>([])
  const [newComment, setNewComment] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [isCommentPosting, setIsCommentPosting] = useState(false)
  const [currentUserId, setCurrentUserId] = useState<string | null>(null)
  const [replyingTo, setReplyingTo] = useState<string | null>(null)
  const [replyText, setReplyText] = useState('')
  const [isReplyPosting, setIsReplyPosting] = useState(false)
  const addItem = useCartStore((state) => state.addItem)

  useEffect(() => {
    async function fetchUserAndArtwork() {
      const supabase = createClient()
      const { data: { user } } = await supabase.auth.getUser()
      setCurrentUserId(user?.id || null)

      const result = await getArtworkDetails(id)
      
      if (result.error) {
        setError(result.error)
      } else if (result.artwork) {
        setArtwork(result.artwork)
        setLikeCount(result.artwork.reactions.likeCount)
        setDislikeCount(result.artwork.reactions.dislikeCount)
        setComments(result.artwork.comments)
        // Set initial user reaction if exists
        if (user) {
          const reactions = result.artwork.reactions.userReactions || []
          const userReaction = reactions.find((r: any) => r.user_id === user.id)?.type || null
          setUserReaction(userReaction)
        }
      }
    }

    fetchUserAndArtwork()
  }, [id])

  const handleReactionClick = async (type: 'like' | 'dislike') => {
    if (!artwork) return

    try {
      const result = await handleReaction(artwork.id, type)
      if (result.error) {
        toast.error(result.error)
        return
      }

      // Update counts based on previous reaction
      if (type === 'like') {
        if (userReaction === 'dislike') {
          setLikeCount(prev => prev + 1)
          setDislikeCount(prev => prev - 1)
        } else if (userReaction === 'like') {
          setLikeCount(prev => prev - 1)
          setUserReaction(null)
          return
        } else {
          setLikeCount(prev => prev + 1)
        }
      } else {
        if (userReaction === 'like') {
          setDislikeCount(prev => prev + 1)
          setLikeCount(prev => prev - 1)
        } else if (userReaction === 'dislike') {
          setDislikeCount(prev => prev - 1)
          setUserReaction(null)
          return
        } else {
          setDislikeCount(prev => prev + 1)
        }
      }

      setUserReaction(type)
      toast.success(result.success)
    } catch (err: any) {
      toast.error(err.message || 'Failed to update reaction')
    }
  }

  const handleAddComment = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!artwork || !newComment.trim() || isCommentPosting) return

    setIsCommentPosting(true)
    try {
      const result = await addComment(artwork.id, newComment.trim())
      if (result.error) {
        toast.error(result.error)
        return
      }

      // Refresh artwork details to get updated comments
      const updatedArtwork = await getArtworkDetails(id)
      if (updatedArtwork.artwork) {
        setComments(updatedArtwork.artwork.comments)
      }

      setNewComment('')
      toast.success('Comment posted successfully!')
    } catch (err: any) {
      toast.error(err.message || 'Failed to add comment')
    } finally {
      setIsCommentPosting(false)
    }
  }

  const handleCommentReaction = async (commentId: string, type: 'like' | 'dislike') => {
    try {
      const result = await handleCommentReactionApi(commentId, type)
      if (result.error) {
        toast.error(result.error)
        return
      }

      // Refresh artwork details to get updated comments
      const updatedArtwork = await getArtworkDetails(id)
      if (updatedArtwork.artwork) {
        setComments(updatedArtwork.artwork.comments)
      }

      toast.success(result.success)
    } catch (err: any) {
      toast.error(err.message || 'Failed to update reaction')
    }
  }

  const handleReply = async (commentId: string) => {
    if (!replyText.trim() || isReplyPosting) return

    setIsReplyPosting(true)
    try {
      const result = await addReply(commentId, replyText.trim())
      if (result.error) {
        toast.error(result.error)
        return
      }

      // Refresh artwork details to get updated comments
      const updatedArtwork = await getArtworkDetails(id)
      if (updatedArtwork.artwork) {
        setComments(updatedArtwork.artwork.comments)
      }

      setReplyText('')
      setReplyingTo(null)
      toast.success('Reply posted successfully!')
    } catch (err: any) {
      toast.error(err.message || 'Failed to add reply')
    } finally {
      setIsReplyPosting(false)
    }
  }

  const handleAddToCart = () => {
    if (!artwork) return
    
    addItem({
      id: artwork.id,
      title: artwork.title,
      price: artwork.price,
      image: artwork.images[0],
      artistId: artwork.artist.id,
    })
    
    toast.success('Added to cart!')
  }

  if (error || !artwork) {
    return (
      <div className="max-w-7xl mx-auto px-4 py-6">
        <div className="text-center text-red-500">
          {error || 'Artwork not found'}
        </div>
      </div>
    )
  }

  const isOwner = currentUserId === artwork.artist.id

  return (
    <div className="max-w-7xl mx-auto px-4 py-6 grid lg:grid-cols-3 gap-6">
      {/* Main Content */}
      <div className="lg:col-span-2 space-y-6">
        <ImageCarousel images={artwork.images} />

        {/* Title and Price */}
        <div className="flex justify-between items-start">
          <h1 className="text-2xl font-bold">{artwork.title}</h1>
          <div className="text-right">
            <p className="text-2xl font-bold">${artwork.price.toFixed(2)}</p>
            {!isOwner && (
              <Button
                className="mt-2 w-full"
                onClick={handleAddToCart}
              >
                <ShoppingCart className="w-4 h-4 mr-2" />
                Add to Cart
              </Button>
            )}
          </div>
        </div>

        { (
          <div className="flex items-center gap-4">
            {/* Like */}
            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                size="icon"
                className={userReaction === 'like' ? 'text-blue-500' : ''}
                onClick={() => handleReactionClick('like')}
              >
                <ThumbsUp className="w-5 h-5" />
              </Button>
              <span className="text-sm">{likeCount}</span>
            </div>

            {/* Dislike */}
            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                size="icon"
                className={userReaction === 'dislike' ? 'text-red-500' : ''}
                onClick={() => handleReactionClick('dislike')}
              >
                <ThumbsDown className="w-5 h-5" />
              </Button>
              <span className="text-sm">{dislikeCount}</span>
            </div>

            <Button variant="secondary" className="flex items-center gap-2">
              <Plus className="w-4 h-4 text-blue-950" />
              Follow {artwork.artist.name}
            </Button>
          </div>
        )}

        {/* Description */}
        <div>
          <h3 className="text-lg font-semibold mb-2">Description</h3>
          <p className="text-sm text-muted-foreground">{artwork.description}</p>
        </div>

        {/* Comments */}
        <div>
          <h3 className="text-lg font-semibold mb-2">Comments</h3>
          <div className="space-y-4">
            {comments.map((comment) => {
              const isCommentOwner = currentUserId === comment.user_id
              return (
                <div key={comment.id}>
                  <div className="p-4 bg-muted rounded-md flex gap-4">
                    <Avatar>
                      <AvatarImage src={comment.avatar_url} />
                      <AvatarFallback>
                        {comment.name[0]?.toUpperCase()}
                      </AvatarFallback>
                    </Avatar>
                    <div className="flex-1 space-y-1">
                      <div className="flex justify-between items-center">
                        <p className="text-sm font-medium">{comment.name}</p>
                      </div>
                      <p className="text-sm text-muted-foreground">
                        {comment.comment}
                      </p>
                      {!isCommentOwner && (
                        <div className="flex items-center gap-2 mt-1">
                          <div className="flex items-center gap-1">
                            <Button 
                              variant="ghost" 
                              size="icon"
                              onClick={() => handleCommentReaction(comment.id, 'like')}
                              className={comment.userReaction === 'like' ? 'text-blue-500' : ''}
                            >
                              <ThumbsUp className="w-4 h-4" />
                            </Button>
                            <span className="text-sm">{comment.likeCount}</span>
                          </div>
                          <div className="flex items-center gap-1">
                            <Button 
                              variant="ghost" 
                              size="icon"
                              onClick={() => handleCommentReaction(comment.id, 'dislike')}
                              className={comment.userReaction === 'dislike' ? 'text-red-500' : ''}
                            >
                              <ThumbsDown className="w-4 h-4" />
                            </Button>
                            <span className="text-sm">{comment.dislikeCount}</span>
                          </div>
                          <Button 
                            variant="ghost" 
                            size="sm" 
                            className="text-xs px-2 py-0 h-6"
                            onClick={() => setReplyingTo(comment.id)}
                          >
                            Reply
                          </Button>
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Reply Form */}
                  {replyingTo === comment.id && (
                    <form 
                      onSubmit={(e) => {
                        e.preventDefault()
                        handleReply(comment.id)
                      }} 
                      className="mt-2 ml-12 flex items-center gap-2"
                    >
                      <Input
                        value={replyText}
                        onChange={(e) => setReplyText(e.target.value)}
                        placeholder="Write a reply..."
                        className="flex-1"
                      />
                      <Button 
                        size="sm" 
                        type="submit" 
                        disabled={isReplyPosting}
                      >
                        {isReplyPosting ? 'Posting...' : 'Reply'}
                      </Button>
                      <Button
                        size="sm"
                        variant="ghost"
                        type="button"
                        onClick={() => {
                          setReplyingTo(null)
                          setReplyText('')
                        }}
                      >
                        Cancel
                      </Button>
                    </form>
                  )}

                  {/* Replies */}
                  {comment.replies && comment.replies.length > 0 && (
                    <div className="ml-12 mt-2 space-y-2">
                      {comment.replies.map((reply) => {
                        const isReplyOwner = currentUserId === reply.user_id
                        return (
                          <div
                            key={reply.id}
                            className="p-3 bg-muted/50 rounded-md flex gap-3"
                          >
                            <Avatar className="w-6 h-6">
                              <AvatarImage src={reply.avatar_url} />
                              <AvatarFallback>
                                {reply.name[0]?.toUpperCase()}
                              </AvatarFallback>
                            </Avatar>
                            <div className="flex-1 space-y-1">
                              <div className="flex justify-between items-center">
                                <p className="text-sm font-medium">{reply.name}</p>
                              </div>
                              <p className="text-sm text-muted-foreground">
                                {reply.comment}
                              </p>
                              {!isReplyOwner && (
                                <div className="flex items-center gap-2">
                                  <div className="flex items-center gap-1">
                                    <Button 
                                      variant="ghost" 
                                      size="icon"
                                      onClick={() => handleCommentReaction(reply.id, 'like')}
                                      className={reply.userReaction === 'like' ? 'text-blue-500' : ''}
                                    >
                                      <ThumbsUp className="w-3 h-3" />
                                    </Button>
                                    <span className="text-xs">{reply.likeCount}</span>
                                  </div>
                                  <div className="flex items-center gap-1">
                                    <Button 
                                      variant="ghost" 
                                      size="icon"
                                      onClick={() => handleCommentReaction(reply.id, 'dislike')}
                                      className={reply.userReaction === 'dislike' ? 'text-red-500' : ''}
                                    >
                                      <ThumbsDown className="w-3 h-3" />
                                    </Button>
                                    <span className="text-xs">{reply.dislikeCount}</span>
                                  </div>
                                </div>
                              )}
                            </div>
                          </div>
                        )
                      })}
                    </div>
                  )}
                </div>
              )
            })}
          </div>
          {!isOwner && (
            <form onSubmit={handleAddComment} className="mt-4 flex items-center gap-2">
              <Input
                value={newComment}
                onChange={(e) => setNewComment(e.target.value)}
                placeholder="Add a comment..."
              />
              <Button size="sm" type="submit" disabled={isCommentPosting}>
                {isCommentPosting ? 'Posting...' : 'Post'}
              </Button>
            </form>
          )}
        </div>
      </div>

      {/* Sidebar */}
      <div className="space-y-6">
        {/* Artist Info */}te_not_found&error_des
        <div>
          <h4 className="font-semibold mb-2">
            More by {artwork.artist.name}
          </h4>
          <div className="grid gap-4">
            {artwork.relatedArtworks.map((art) => (
              <Link
                key={art.id}
                href={`/art-details/${art.id}`}
                className="block group"
              >
                <Card className="overflow-hidden">
                  <div className="relative aspect-square">
                    <Image
                      src={art.image}
                      alt={art.title}
                      fill
                      className="object-cover transition-transform group-hover:scale-105"
                    />
                  </div>
                  <div className="p-2">
                    <p className="font-medium truncate">{art.title}</p>
                  </div>
                </Card>
              </Link>
            ))}
          </div>
        </div>

        {/* Same Category */}
        <div>
          <h4 className="font-semibold mb-2">More in {artwork.category}</h4>
          {/* TODO: Add same category artworks */}
        </div>
        <Toaster />
      </div>
    </div>
  )
}

// artisan-alley/src/views/ArtDetails.vue
<template>
  <div class="max-w-7xl mx-auto px-4 py-6 grid lg:grid-cols-3 gap-6" v-if="art">
    <!-- Main Content -->
    <div class="lg:col-span-2 space-y-6">
      <ArtCarousel :images="art.images" />

      <!-- Title -->
      <h1 class="text-2xl font-bold">{{ art.title }}</h1>

      <!-- Creator actions -->
      <div class="flex items-center gap-4">
        <!-- Like -->
        <div class="flex items-center gap-2">
          <Button
            variant="ghost"
            size="icon"
            :disabled="art?.value?.user_id === user.value?.id"
            :class="{ 'text-blue-500': userReaction === 'like' }"
            @click="handleReaction('like')"
          >
            <ThumbsUpIcon class="w-5 h-5" />
          </Button>
          <span class="text-sm">{{ likeCount }}</span>
        </div>

        <!-- Dislike -->
        <div class="flex items-center gap-2">
          <Button
            variant="ghost"
            size="icon"
            :disabled="art?.value?.user_id === user.value?.id"
            :class="{ 'text-red-500': userReaction === 'dislike' }"
            @click="handleReaction('dislike')"
          >
            <ThumbsDownIcon class="w-5 h-5" />
          </Button>
          <span class="text-sm">{{ dislikeCount }}</span>
        </div>

        <Button variant="secondary" class="flex items-center gap-2">
          <Plus class="w-4 h-4 text-blue-950" />
          Follow {{ art.creator?.name || "Artist" }}
        </Button>
      </div>

      <!-- Description -->
      <div>
        <h3 class="text-lg font-semibold mb-2">Description</h3>
        <p class="text-sm text-muted-foreground">{{ art.description }}</p>
      </div>

      <!-- Comments -->
      <div>
        <h3 class="text-lg font-semibold mb-2">Comments</h3>
        <div class="space-y-4">
          <div
            v-for="comment in comments"
            :key="comment.id"
            class="p-4 bg-muted rounded-md flex gap-4"
          >
            <img
              :src="comment.avatar_url"
              class="w-10 h-10 rounded-full object-cover"
              alt="Avatar"
            />
            <div class="flex-1 space-y-1">
              <div class="flex justify-between items-center">
                <p class="text-sm font-medium">{{ comment.name }}</p>
              </div>
              <p class="text-sm text-muted-foreground">
                {{ comment.comment }}
              </p>
              <div class="flex items-center gap-2 mt-1">
                <Button variant="ghost" size="icon">
                  <ThumbsUpIcon class="w-4 h-4" />
                </Button>
                <Button variant="ghost" size="icon">
                  <ThumbsDownIcon class="w-4 h-4" />
                </Button>
                <Button variant="ghost" size="sm" class="text-xs px-2 py-0 h-6">
                  Reply
                </Button>
              </div>
            </div>
          </div>
        </div>
        <form v-if="art.value?.user_id !== user.value?.id" @submit.prevent="addComment" class="mt-4 flex items-center gap-2">
          <Input v-model="newComment" placeholder="Add a comment..." />
          <Button size="sm" type="submit">Post</Button>
        </form>
      </div>
    </div>

    <!-- Sidebar -->
    <div class="space-y-6">
      <!-- Same Artist -->
      <div>
        <h4 class="font-semibold mb-2">
          More by {{ art.creator?.name || "Artist" }}
        </h4>
        <RouterLink
          v-for="a in sameArtistWorks"
          :key="a.id"
          :to="`/art-details/${a.id}`"
          class="rounded overflow-hidden shadow-md block hover:shadow-lg transition"
        >
          <img
            :src="a.images[0]"
            :alt="a.title"
            class="w-full h-48 object-cover bg-gray-100"
          />
          <div class="p-2 text-sm font-medium truncate">
            {{ a.title }}
          </div>
        </RouterLink>
      </div>

      <!-- Same Category -->
      <div>
        <h4 class="font-semibold mb-2">More in {{ art.category }}</h4>
        <RouterLink
          v-for="a in sameCategoryWorks"
          :key="a.id"
          :to="`/art-details/${a.id}`"
          class="rounded overflow-hidden shadow-md block hover:shadow-lg transition"
        >
          <img
            :src="a.images[0]"
            :alt="a.title"
            class="w-full h-48 object-cover bg-gray-100"
          />
          <div class="p-2 text-sm font-medium truncate">
            {{ a.title }}
          </div>
        </RouterLink>
      </div>
    </div>
  </div>

  <div v-else class="text-center py-10 text-gray-500">Loading artwork...</div>
</template>
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { useRoute } from "vue-router";
import { supabase } from "@/lib/supabase";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import ArtCarousel from "@/components/Carousel.vue";
import { Plus, ThumbsDownIcon, ThumbsUpIcon } from "lucide-vue-next";
import { toast } from "vue-sonner";

const route = useRoute();

const art = ref<any>(null);
const sameArtistWorks = ref<any[]>([]);
const sameCategoryWorks = ref<any[]>([]);
const comments = ref<any[]>([]);
const newComment = ref("");

const likeCount = ref(0);
const dislikeCount = ref(0);
const userReaction = ref<string | null>(null);
const user = ref<any>(null);

const fetchCurrentUser = async () => {
  const { data } = await supabase.auth.getUser();
  user.value = data.user;
};

const fetchArt = async () => {
  const { data, error } = await supabase
    .from("ArtPiece")
    .select(
      `
      id,
      title,
      description,
      images,
      category,
      user_id,
      Reaction(type, user_id),
      Comment(*)
      `
    )
    .eq("id", route.params.id)
    .single();

  if (error) {
    console.error(error);
    return;
  }

  art.value = data;

  // Extract reactions
  const allReactions = data.Reaction || [];
  likeCount.value = allReactions.filter((r: any) => r.type === "like").length;
  dislikeCount.value = allReactions.filter((r: any) => r.type === "dislike").length;

  userReaction.value =
    allReactions.find((r: any) => r.user_id === user.value?.id)?.type || null;

  // Extract comments
  comments.value = data.Comment || [];

  // Fetch sidebar
  const [sameArtist, sameCategory] = await Promise.all([
    supabase
      .from("ArtPiece")
      .select("images, title, id")
      .eq("user_id", data.user_id)
      .neq("id", data.id)
      .limit(4),
    supabase
      .from("ArtPiece")
      .select("images, title, id")
      .eq("category", data.category)
      .neq("id", data.id)
      .limit(4),
  ]);

  sameArtistWorks.value = sameArtist.data || [];
  sameCategoryWorks.value = sameCategory.data || [];
};

const handleReaction = async (type: "like" | "dislike") => {
  if (!user.value || !art.value?.id) return;

  await supabase
    .from("Reaction")
    .upsert(
      [
        {
          art_piece_id: art.value.id,
          user_id: user.value.id,
          type,
        },
      ],
      { onConflict: "art_piece_id, user_id" }
    );

  userReaction.value = type;

  // Update reaction counts manually
  if (type === "like") {
    likeCount.value += userReaction.value === "dislike" ? 1 : 0;
    dislikeCount.value -= userReaction.value === "dislike" ? 1 : 0;
  } else {
    dislikeCount.value += userReaction.value === "like" ? 1 : 0;
    likeCount.value -= userReaction.value === "like" ? 1 : 0;
  }

  await fetchArt(); // re-fetch to stay consistent
};

const addComment = async () => {
  if (art.value.user_id === user.value?.id) {
    toast.error("You cannot comment on your own artwork");
    return;
  }

  if (!newComment.value.trim() || !user.value || !art.value?.id) return;

  const { error } = await supabase.from("Comment").insert([
    {
      art_piece_id: art.value.id,
      user_id: user.value.id,
      comment: newComment.value,
      avatar_url: user.value.user_metadata.avatar_url,
      name: user.value.user_metadata.name,
    },
  ]);

  if (!error) {
    newComment.value = "";
    await fetchArt(); // refresh to get updated comments
  }
};

onMounted(async () => {
  await fetchCurrentUser();
  await fetchArt();
});
</script>
